server:
  port: 18081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/Delivery_platform?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      max-lifetime: 500000
  redis:
    database: 3
    host: localhost
    port: 6379
    timeout: 5000
    password: root
  servlet:
    multipart:
      max-file-size: 50MB     #单个最大文件大小，默认是1MB
      max-request-size: 100MB   #总请求文件大小
  application:
    name: chat-base
  main:
    allow-circular-references=true:
mybatis:
  type-aliases-package: com.demo1.Entity
  mapper-locations: classpath:/mybatis/*.xml
files:
  upload:
    path: D:\files2\
eureka:
  instance:
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则），默认30
    lease-renewal-interval-in-seconds: 10
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己），默认90
    lease-expiration-duration-in-seconds: 12
  client:
    registry-fetch-interval-seconds: 10 #eureka client刷新本地缓存时间，默认30
    serviceUrl:
      defaultZone: http://localhost:18090/eureka/
# 日志记录输出配置
logging:
  level:
    com:
      example:
        websocket_service:
          dao: debug

